version: "4.0"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
      - "8080:8080"
    restart: always
    tty: true
    volumes:
      - /config:/config
      - /data:/data
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /config:/config
      - /data:/data

volumes:
  config:
  data:
